name: Build and Release Binaries

on:
  push:
    tags:
      - 'v*.*.*'  # This triggers on version tags (e.g., v1.0.0)
  workflow_dispatch:  # Also allow manual triggering from the GitHub UI

jobs:
  build:
    strategy:
      matrix:
        platform: [ linux-amd64, linux-arm64, windows-amd64 ]
    # For Windows, use windows-latest; for Linux targets, use ubuntu-latest.
    runs-on: ${{ matrix.platform == 'windows-amd64' ? 'windows-latest' : 'ubuntu-latest' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Build Fat JAR
        run: ./gradlew clean shadowJar

      # For Linux runners, install native-image if not already available.
      - name: Install GraalVM Native Image
        if: runner.os == 'Linux'
        run: |
          gu install native-image || echo "native-image already installed"
        shell: bash

      - name: Build Native Executable
        run: |
          if [ "${{ matrix.platform }}" == "linux-amd64" ]; then
            echo "Building Linux amd64 binary"
            native-image --no-fallback -jar build/libs/mytool-1.0.0-all.jar mytool-linux-amd64
          elif [ "${{ matrix.platform }}" == "linux-arm64" ]; then
            echo "Building Linux arm64 binary"
            native-image --no-fallback -jar build/libs/mytool-1.0.0-all.jar mytool-linux-arm64
          elif [ "${{ matrix.platform }}" == "windows-amd64" ]; then
            echo "Building Windows amd64 binary"
            native-image --no-fallback -jar build/libs/mytool-1.0.0-all.jar mytool-windows-amd64.exe
          fi
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mytool-${{ matrix.platform }}
          path: |
            mytool-linux-amd64*
            mytool-linux-arm64*
            mytool-windows-amd64*.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
       
