name: Build and Release Binaries

on:
  push:
    tags:
      - 'v*.*.*'  # Automatically triggered when a tag is pushed (e.g., v1.0.0)
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Tag for the release (e.g., v1.0.0)'
        required: false

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: linux-amd64
            runsOn: ubuntu-latest
          - platform: linux-arm64
            runsOn: ubuntu-latest
##          - platform: windows-amd64
##            runsOn: windows-latest
    runs-on: ${{ matrix.runsOn }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          


      # Install native-image using gu
      - name: Install GraalVM Native Image
        if: runner.os == 'Linux'
        run: |
          gu install native-image || echo "native-image already installed"
        shell: bash

      # - name: Install Native Image on Windows
      #   if: runner.os == 'Windows'
      #   run: |
      #     & "$env:GRAALVM_HOME\bin\gu.cmd" install native-image || Write-Host "native-image already installed"
      #   shell: pwsh

          
      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Build Fat JAR
        run: ./gradlew clean shadowJar

      - name: Build Native Executable
        run: |
          if [ "${{ matrix.platform }}" == "linux-amd64" ]; then
            echo "Building Linux amd64 binary"
            native-image --no-fallback -jar build/libs/mytool-1.0.0-all.jar mytool-linux-amd64
          elif [ "${{ matrix.platform }}" == "linux-arm64" ]; then
            echo "Building Linux arm64 binary"
            native-image --no-fallback -jar build/libs/mytool-1.0.0-all.jar mytool-linux-arm64
          fi
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mytool-${{ matrix.platform }}
          path: |
            mytool-linux-amd64*
            mytool-linux-arm64*
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.release_tag || github.ref }}
          release_name: Release ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.release_tag || github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts
          asset_name: mytool-binaries.zip
          asset_content_type: application/zip
